### PR TITLE
Add paddle and brick sound effects

### PR DESCRIPTION
**Pull request by SohamKukreti**
I added collision sound effects when the ball collides with the brick and the paddle to make the game more immersive.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.

* [ ] please comply with imperative tense recommendation and others in how to make commits, and fix the typo in the commit message,
* [ ] the files are wav format, can they be mp3 or ogg instead?
* [ ] please confirm the sounds are your own work so as to comply with the license of the app,

**Comment by SohamKukreti** [comment]
Hi quozl, thanks for the review. It's my first time contributing to sugarlabs so apologies for the mistakes.
I can insert the mp3 or ogg files in the project,that would not be a problem.
These sounds are not my own work, however they are released under Creative Commons 0 "([CC0](https://creativecommons.org/publicdomain/zero/1.0/))" for the paddle sound and Creative Commons Attribution "[CC-BY 3.0](http://creativecommons.org/licenses/by/3.0/)" for the brick hit sound effect. I forgot to credit the owner so I will do that too.

**Comment by SohamKukreti** [comment]
So I've replaced the previous 2 sound effects with ones I have created and also changed the commit message. Please let me know if I have to change anything else.

**Comment by quozl** [comment]
Thanks.  You can use sounds licensed as Creative Commons, but your commit message must say so, a COPYING file next to the sounds should be added, and the `activity/activity.info` tag _license_ may need changing.

**Pull request merged**
