### PR TITLE
Rename files and format with black formatter

### PR DESCRIPTION
**Pull request by sparshg**
@chimosky @srevinsaju Please review
TestGame.py was poorly formatted making it difficult to work with the activity

### CODE REVIEW

**Comment by sparshg** [comment]
We should merge this after other PR's are done as there will me merge conflicts

**Comment by sparshg** [comment]
@chimosky Resolved merge conflicts, not tested though yet.

**Comment by chimosky** [comment]
I should've taken a look at this first before making a release, my bad. Could you rebase with master first?

**Comment by sparshg** [comment]
Rebased to master.

**Comment by chimosky** [comment]
Thanks!

**Pull request merged**
